// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/api/meal.proto

package nutritionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddMealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Calories      float64                `protobuf:"fixed64,2,opt,name=calories,proto3" json:"calories,omitempty"`
	Proteins      float64                `protobuf:"fixed64,3,opt,name=proteins,proto3" json:"proteins,omitempty"`
	Fats          float64                `protobuf:"fixed64,4,opt,name=fats,proto3" json:"fats,omitempty"`
	Carbohydrates float64                `protobuf:"fixed64,5,opt,name=carbohydrates,proto3" json:"carbohydrates,omitempty"`
	WeightGrams   int32                  `protobuf:"varint,6,opt,name=weight_grams,json=weightGrams,proto3" json:"weight_grams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMealRequest) Reset() {
	*x = AddMealRequest{}
	mi := &file_pkg_api_meal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMealRequest) ProtoMessage() {}

func (x *AddMealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_meal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMealRequest.ProtoReflect.Descriptor instead.
func (*AddMealRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_meal_proto_rawDescGZIP(), []int{0}
}

func (x *AddMealRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddMealRequest) GetCalories() float64 {
	if x != nil {
		return x.Calories
	}
	return 0
}

func (x *AddMealRequest) GetProteins() float64 {
	if x != nil {
		return x.Proteins
	}
	return 0
}

func (x *AddMealRequest) GetFats() float64 {
	if x != nil {
		return x.Fats
	}
	return 0
}

func (x *AddMealRequest) GetCarbohydrates() float64 {
	if x != nil {
		return x.Carbohydrates
	}
	return 0
}

func (x *AddMealRequest) GetWeightGrams() int32 {
	if x != nil {
		return x.WeightGrams
	}
	return 0
}

type MealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Calories      float64                `protobuf:"fixed64,3,opt,name=calories,proto3" json:"calories,omitempty"`
	Proteins      float64                `protobuf:"fixed64,4,opt,name=proteins,proto3" json:"proteins,omitempty"`
	Fats          float64                `protobuf:"fixed64,5,opt,name=fats,proto3" json:"fats,omitempty"`
	Carbohydrates float64                `protobuf:"fixed64,6,opt,name=carbohydrates,proto3" json:"carbohydrates,omitempty"`
	WeightGrams   int32                  `protobuf:"varint,7,opt,name=weight_grams,json=weightGrams,proto3" json:"weight_grams,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MealResponse) Reset() {
	*x = MealResponse{}
	mi := &file_pkg_api_meal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealResponse) ProtoMessage() {}

func (x *MealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_meal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealResponse.ProtoReflect.Descriptor instead.
func (*MealResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_meal_proto_rawDescGZIP(), []int{1}
}

func (x *MealResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MealResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MealResponse) GetCalories() float64 {
	if x != nil {
		return x.Calories
	}
	return 0
}

func (x *MealResponse) GetProteins() float64 {
	if x != nil {
		return x.Proteins
	}
	return 0
}

func (x *MealResponse) GetFats() float64 {
	if x != nil {
		return x.Fats
	}
	return 0
}

func (x *MealResponse) GetCarbohydrates() float64 {
	if x != nil {
		return x.Carbohydrates
	}
	return 0
}

func (x *MealResponse) GetWeightGrams() int32 {
	if x != nil {
		return x.WeightGrams
	}
	return 0
}

func (x *MealResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DailyReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Пока заглушка, но в будущем пригодится
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyReportRequest) Reset() {
	*x = DailyReportRequest{}
	mi := &file_pkg_api_meal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyReportRequest) ProtoMessage() {}

func (x *DailyReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_meal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyReportRequest.ProtoReflect.Descriptor instead.
func (*DailyReportRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_meal_proto_rawDescGZIP(), []int{2}
}

func (x *DailyReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DailyReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCalories float64                `protobuf:"fixed64,1,opt,name=total_calories,json=totalCalories,proto3" json:"total_calories,omitempty"`
	TotalProteins float64                `protobuf:"fixed64,2,opt,name=total_proteins,json=totalProteins,proto3" json:"total_proteins,omitempty"`
	TotalFats     float64                `protobuf:"fixed64,3,opt,name=total_fats,json=totalFats,proto3" json:"total_fats,omitempty"`
	TotalCarbs    float64                `protobuf:"fixed64,4,opt,name=total_carbs,json=totalCarbs,proto3" json:"total_carbs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyReportResponse) Reset() {
	*x = DailyReportResponse{}
	mi := &file_pkg_api_meal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyReportResponse) ProtoMessage() {}

func (x *DailyReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_meal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyReportResponse.ProtoReflect.Descriptor instead.
func (*DailyReportResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_meal_proto_rawDescGZIP(), []int{3}
}

func (x *DailyReportResponse) GetTotalCalories() float64 {
	if x != nil {
		return x.TotalCalories
	}
	return 0
}

func (x *DailyReportResponse) GetTotalProteins() float64 {
	if x != nil {
		return x.TotalProteins
	}
	return 0
}

func (x *DailyReportResponse) GetTotalFats() float64 {
	if x != nil {
		return x.TotalFats
	}
	return 0
}

func (x *DailyReportResponse) GetTotalCarbs() float64 {
	if x != nil {
		return x.TotalCarbs
	}
	return 0
}

var File_pkg_api_meal_proto protoreflect.FileDescriptor

const file_pkg_api_meal_proto_rawDesc = "" +
	"\n" +
	"\x12pkg/api/meal.proto\x12\tnutrition\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x01\n" +
	"\x0eAddMealRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcalories\x18\x02 \x01(\x01R\bcalories\x12\x1a\n" +
	"\bproteins\x18\x03 \x01(\x01R\bproteins\x12\x12\n" +
	"\x04fats\x18\x04 \x01(\x01R\x04fats\x12$\n" +
	"\rcarbohydrates\x18\x05 \x01(\x01R\rcarbohydrates\x12!\n" +
	"\fweight_grams\x18\x06 \x01(\x05R\vweightGrams\"\x82\x02\n" +
	"\fMealResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcalories\x18\x03 \x01(\x01R\bcalories\x12\x1a\n" +
	"\bproteins\x18\x04 \x01(\x01R\bproteins\x12\x12\n" +
	"\x04fats\x18\x05 \x01(\x01R\x04fats\x12$\n" +
	"\rcarbohydrates\x18\x06 \x01(\x01R\rcarbohydrates\x12!\n" +
	"\fweight_grams\x18\a \x01(\x05R\vweightGrams\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"-\n" +
	"\x12DailyReportRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xa3\x01\n" +
	"\x13DailyReportResponse\x12%\n" +
	"\x0etotal_calories\x18\x01 \x01(\x01R\rtotalCalories\x12%\n" +
	"\x0etotal_proteins\x18\x02 \x01(\x01R\rtotalProteins\x12\x1d\n" +
	"\n" +
	"total_fats\x18\x03 \x01(\x01R\ttotalFats\x12\x1f\n" +
	"\vtotal_carbs\x18\x04 \x01(\x01R\n" +
	"totalCarbs2\xa2\x01\n" +
	"\x10NutritionService\x12=\n" +
	"\aAddMeal\x12\x19.nutrition.AddMealRequest\x1a\x17.nutrition.MealResponse\x12O\n" +
	"\x0eGetDailyReport\x12\x1d.nutrition.DailyReportRequest\x1a\x1e.nutrition.DailyReportResponseB/Z-fitbank/nutrition-service/pkg/api;nutritionpbb\x06proto3"

var (
	file_pkg_api_meal_proto_rawDescOnce sync.Once
	file_pkg_api_meal_proto_rawDescData []byte
)

func file_pkg_api_meal_proto_rawDescGZIP() []byte {
	file_pkg_api_meal_proto_rawDescOnce.Do(func() {
		file_pkg_api_meal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_meal_proto_rawDesc), len(file_pkg_api_meal_proto_rawDesc)))
	})
	return file_pkg_api_meal_proto_rawDescData
}

var file_pkg_api_meal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_api_meal_proto_goTypes = []any{
	(*AddMealRequest)(nil),        // 0: nutrition.AddMealRequest
	(*MealResponse)(nil),          // 1: nutrition.MealResponse
	(*DailyReportRequest)(nil),    // 2: nutrition.DailyReportRequest
	(*DailyReportResponse)(nil),   // 3: nutrition.DailyReportResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_pkg_api_meal_proto_depIdxs = []int32{
	4, // 0: nutrition.MealResponse.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: nutrition.NutritionService.AddMeal:input_type -> nutrition.AddMealRequest
	2, // 2: nutrition.NutritionService.GetDailyReport:input_type -> nutrition.DailyReportRequest
	1, // 3: nutrition.NutritionService.AddMeal:output_type -> nutrition.MealResponse
	3, // 4: nutrition.NutritionService.GetDailyReport:output_type -> nutrition.DailyReportResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_api_meal_proto_init() }
func file_pkg_api_meal_proto_init() {
	if File_pkg_api_meal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_meal_proto_rawDesc), len(file_pkg_api_meal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_meal_proto_goTypes,
		DependencyIndexes: file_pkg_api_meal_proto_depIdxs,
		MessageInfos:      file_pkg_api_meal_proto_msgTypes,
	}.Build()
	File_pkg_api_meal_proto = out.File
	file_pkg_api_meal_proto_goTypes = nil
	file_pkg_api_meal_proto_depIdxs = nil
}
