// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: pkg/api/meal.proto

package nutritionpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NutritionService_AddMeal_FullMethodName        = "/nutrition.NutritionService/AddMeal"
	NutritionService_GetDailyReport_FullMethodName = "/nutrition.NutritionService/GetDailyReport"
)

// NutritionServiceClient is the client API for NutritionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис для учета питания
type NutritionServiceClient interface {
	// Добавить прием пищи
	AddMeal(ctx context.Context, in *AddMealRequest, opts ...grpc.CallOption) (*MealResponse, error)
	// Получить отчет за день (сколько всего съедено)
	GetDailyReport(ctx context.Context, in *DailyReportRequest, opts ...grpc.CallOption) (*DailyReportResponse, error)
}

type nutritionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNutritionServiceClient(cc grpc.ClientConnInterface) NutritionServiceClient {
	return &nutritionServiceClient{cc}
}

func (c *nutritionServiceClient) AddMeal(ctx context.Context, in *AddMealRequest, opts ...grpc.CallOption) (*MealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MealResponse)
	err := c.cc.Invoke(ctx, NutritionService_AddMeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nutritionServiceClient) GetDailyReport(ctx context.Context, in *DailyReportRequest, opts ...grpc.CallOption) (*DailyReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DailyReportResponse)
	err := c.cc.Invoke(ctx, NutritionService_GetDailyReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NutritionServiceServer is the server API for NutritionService service.
// All implementations must embed UnimplementedNutritionServiceServer
// for forward compatibility.
//
// Сервис для учета питания
type NutritionServiceServer interface {
	// Добавить прием пищи
	AddMeal(context.Context, *AddMealRequest) (*MealResponse, error)
	// Получить отчет за день (сколько всего съедено)
	GetDailyReport(context.Context, *DailyReportRequest) (*DailyReportResponse, error)
	mustEmbedUnimplementedNutritionServiceServer()
}

// UnimplementedNutritionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNutritionServiceServer struct{}

func (UnimplementedNutritionServiceServer) AddMeal(context.Context, *AddMealRequest) (*MealResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMeal not implemented")
}
func (UnimplementedNutritionServiceServer) GetDailyReport(context.Context, *DailyReportRequest) (*DailyReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDailyReport not implemented")
}
func (UnimplementedNutritionServiceServer) mustEmbedUnimplementedNutritionServiceServer() {}
func (UnimplementedNutritionServiceServer) testEmbeddedByValue()                          {}

// UnsafeNutritionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NutritionServiceServer will
// result in compilation errors.
type UnsafeNutritionServiceServer interface {
	mustEmbedUnimplementedNutritionServiceServer()
}

func RegisterNutritionServiceServer(s grpc.ServiceRegistrar, srv NutritionServiceServer) {
	// If the following call panics, it indicates UnimplementedNutritionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NutritionService_ServiceDesc, srv)
}

func _NutritionService_AddMeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NutritionServiceServer).AddMeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NutritionService_AddMeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NutritionServiceServer).AddMeal(ctx, req.(*AddMealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NutritionService_GetDailyReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DailyReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NutritionServiceServer).GetDailyReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NutritionService_GetDailyReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NutritionServiceServer).GetDailyReport(ctx, req.(*DailyReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NutritionService_ServiceDesc is the grpc.ServiceDesc for NutritionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NutritionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nutrition.NutritionService",
	HandlerType: (*NutritionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMeal",
			Handler:    _NutritionService_AddMeal_Handler,
		},
		{
			MethodName: "GetDailyReport",
			Handler:    _NutritionService_GetDailyReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/meal.proto",
}
