// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/api/activity.proto

package activitypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос может быть пустым (получить всё) или с фильтрами
type ListActivitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivitiesRequest) Reset() {
	*x = ListActivitiesRequest{}
	mi := &file_pkg_api_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivitiesRequest) ProtoMessage() {}

func (x *ListActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivitiesRequest.ProtoReflect.Descriptor instead.
func (*ListActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_activity_proto_rawDescGZIP(), []int{0}
}

func (x *ListActivitiesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListActivitiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// repeated — это аналог слайса ([]ActivityResponse) в Go
	Activities    []*ActivityResponse `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivitiesResponse) Reset() {
	*x = ListActivitiesResponse{}
	mi := &file_pkg_api_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivitiesResponse) ProtoMessage() {}

func (x *ListActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivitiesResponse.ProtoReflect.Descriptor instead.
func (*ListActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_activity_proto_rawDescGZIP(), []int{1}
}

func (x *ListActivitiesResponse) GetActivities() []*ActivityResponse {
	if x != nil {
		return x.Activities
	}
	return nil
}

// Сообщения запросов и ответов
type CreateActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Weight        float64                `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	Reps          int32                  `protobuf:"varint,3,opt,name=reps,proto3" json:"reps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateActivityRequest) Reset() {
	*x = CreateActivityRequest{}
	mi := &file_pkg_api_activity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActivityRequest) ProtoMessage() {}

func (x *CreateActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_activity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActivityRequest.ProtoReflect.Descriptor instead.
func (*CreateActivityRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_activity_proto_rawDescGZIP(), []int{2}
}

func (x *CreateActivityRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateActivityRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreateActivityRequest) GetReps() int32 {
	if x != nil {
		return x.Reps
	}
	return 0
}

type GetActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityRequest) Reset() {
	*x = GetActivityRequest{}
	mi := &file_pkg_api_activity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityRequest) ProtoMessage() {}

func (x *GetActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_activity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityRequest.ProtoReflect.Descriptor instead.
func (*GetActivityRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_activity_proto_rawDescGZIP(), []int{3}
}

func (x *GetActivityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Weight        float64                `protobuf:"fixed64,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Reps          int32                  `protobuf:"varint,4,opt,name=reps,proto3" json:"reps,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityResponse) Reset() {
	*x = ActivityResponse{}
	mi := &file_pkg_api_activity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityResponse) ProtoMessage() {}

func (x *ActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_activity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityResponse.ProtoReflect.Descriptor instead.
func (*ActivityResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_activity_proto_rawDescGZIP(), []int{4}
}

func (x *ActivityResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActivityResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ActivityResponse) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ActivityResponse) GetReps() int32 {
	if x != nil {
		return x.Reps
	}
	return 0
}

func (x *ActivityResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_pkg_api_activity_proto protoreflect.FileDescriptor

const file_pkg_api_activity_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/api/activity.proto\x12\bactivity\x1a\x1fgoogle/protobuf/timestamp.proto\"0\n" +
	"\x15ListActivitiesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"T\n" +
	"\x16ListActivitiesResponse\x12:\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\x1a.activity.ActivityResponseR\n" +
	"activities\"W\n" +
	"\x15CreateActivityRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x01R\x06weight\x12\x12\n" +
	"\x04reps\x18\x03 \x01(\x05R\x04reps\"$\n" +
	"\x12GetActivityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9d\x01\n" +
	"\x10ActivityResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x01R\x06weight\x12\x12\n" +
	"\x04reps\x18\x04 \x01(\x05R\x04reps\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xfe\x01\n" +
	"\x0fActivityService\x12M\n" +
	"\x0eCreateActivity\x12\x1f.activity.CreateActivityRequest\x1a\x1a.activity.ActivityResponse\x12G\n" +
	"\vGetActivity\x12\x1c.activity.GetActivityRequest\x1a\x1a.activity.ActivityResponse\x12S\n" +
	"\x0eListActivities\x12\x1f.activity.ListActivitiesRequest\x1a .activity.ListActivitiesResponseB-Z+fitbank/activity-service/pkg/api;activitypbb\x06proto3"

var (
	file_pkg_api_activity_proto_rawDescOnce sync.Once
	file_pkg_api_activity_proto_rawDescData []byte
)

func file_pkg_api_activity_proto_rawDescGZIP() []byte {
	file_pkg_api_activity_proto_rawDescOnce.Do(func() {
		file_pkg_api_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_activity_proto_rawDesc), len(file_pkg_api_activity_proto_rawDesc)))
	})
	return file_pkg_api_activity_proto_rawDescData
}

var file_pkg_api_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_api_activity_proto_goTypes = []any{
	(*ListActivitiesRequest)(nil),  // 0: activity.ListActivitiesRequest
	(*ListActivitiesResponse)(nil), // 1: activity.ListActivitiesResponse
	(*CreateActivityRequest)(nil),  // 2: activity.CreateActivityRequest
	(*GetActivityRequest)(nil),     // 3: activity.GetActivityRequest
	(*ActivityResponse)(nil),       // 4: activity.ActivityResponse
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_pkg_api_activity_proto_depIdxs = []int32{
	4, // 0: activity.ListActivitiesResponse.activities:type_name -> activity.ActivityResponse
	5, // 1: activity.ActivityResponse.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: activity.ActivityService.CreateActivity:input_type -> activity.CreateActivityRequest
	3, // 3: activity.ActivityService.GetActivity:input_type -> activity.GetActivityRequest
	0, // 4: activity.ActivityService.ListActivities:input_type -> activity.ListActivitiesRequest
	4, // 5: activity.ActivityService.CreateActivity:output_type -> activity.ActivityResponse
	4, // 6: activity.ActivityService.GetActivity:output_type -> activity.ActivityResponse
	1, // 7: activity.ActivityService.ListActivities:output_type -> activity.ListActivitiesResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_api_activity_proto_init() }
func file_pkg_api_activity_proto_init() {
	if File_pkg_api_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_activity_proto_rawDesc), len(file_pkg_api_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_activity_proto_goTypes,
		DependencyIndexes: file_pkg_api_activity_proto_depIdxs,
		MessageInfos:      file_pkg_api_activity_proto_msgTypes,
	}.Build()
	File_pkg_api_activity_proto = out.File
	file_pkg_api_activity_proto_goTypes = nil
	file_pkg_api_activity_proto_depIdxs = nil
}
