// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/activity.proto

package activitypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщения запросов и ответов
type CreateActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Weight        float64                `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	Reps          int32                  `protobuf:"varint,3,opt,name=reps,proto3" json:"reps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateActivityRequest) Reset() {
	*x = CreateActivityRequest{}
	mi := &file_api_proto_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActivityRequest) ProtoMessage() {}

func (x *CreateActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActivityRequest.ProtoReflect.Descriptor instead.
func (*CreateActivityRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_activity_proto_rawDescGZIP(), []int{0}
}

func (x *CreateActivityRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateActivityRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreateActivityRequest) GetReps() int32 {
	if x != nil {
		return x.Reps
	}
	return 0
}

type GetActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityRequest) Reset() {
	*x = GetActivityRequest{}
	mi := &file_api_proto_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityRequest) ProtoMessage() {}

func (x *GetActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityRequest.ProtoReflect.Descriptor instead.
func (*GetActivityRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_activity_proto_rawDescGZIP(), []int{1}
}

func (x *GetActivityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Weight        float64                `protobuf:"fixed64,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Reps          int32                  `protobuf:"varint,4,opt,name=reps,proto3" json:"reps,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityResponse) Reset() {
	*x = ActivityResponse{}
	mi := &file_api_proto_activity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityResponse) ProtoMessage() {}

func (x *ActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_activity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityResponse.ProtoReflect.Descriptor instead.
func (*ActivityResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_activity_proto_rawDescGZIP(), []int{2}
}

func (x *ActivityResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActivityResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ActivityResponse) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ActivityResponse) GetReps() int32 {
	if x != nil {
		return x.Reps
	}
	return 0
}

func (x *ActivityResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_api_proto_activity_proto protoreflect.FileDescriptor

const file_api_proto_activity_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/activity.proto\x12\bactivity\x1a\x1fgoogle/protobuf/timestamp.proto\"W\n" +
	"\x15CreateActivityRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x01R\x06weight\x12\x12\n" +
	"\x04reps\x18\x03 \x01(\x05R\x04reps\"$\n" +
	"\x12GetActivityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9d\x01\n" +
	"\x10ActivityResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x01R\x06weight\x12\x12\n" +
	"\x04reps\x18\x04 \x01(\x05R\x04reps\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xa9\x01\n" +
	"\x0fActivityService\x12M\n" +
	"\x0eCreateActivity\x12\x1f.activity.CreateActivityRequest\x1a\x1a.activity.ActivityResponse\x12G\n" +
	"\vGetActivity\x12\x1c.activity.GetActivityRequest\x1a\x1a.activity.ActivityResponseB-Z+fitbank/activity-service/pkg/api;activitypbb\x06proto3"

var (
	file_api_proto_activity_proto_rawDescOnce sync.Once
	file_api_proto_activity_proto_rawDescData []byte
)

func file_api_proto_activity_proto_rawDescGZIP() []byte {
	file_api_proto_activity_proto_rawDescOnce.Do(func() {
		file_api_proto_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_activity_proto_rawDesc), len(file_api_proto_activity_proto_rawDesc)))
	})
	return file_api_proto_activity_proto_rawDescData
}

var file_api_proto_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_activity_proto_goTypes = []any{
	(*CreateActivityRequest)(nil), // 0: activity.CreateActivityRequest
	(*GetActivityRequest)(nil),    // 1: activity.GetActivityRequest
	(*ActivityResponse)(nil),      // 2: activity.ActivityResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_api_proto_activity_proto_depIdxs = []int32{
	3, // 0: activity.ActivityResponse.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: activity.ActivityService.CreateActivity:input_type -> activity.CreateActivityRequest
	1, // 2: activity.ActivityService.GetActivity:input_type -> activity.GetActivityRequest
	2, // 3: activity.ActivityService.CreateActivity:output_type -> activity.ActivityResponse
	2, // 4: activity.ActivityService.GetActivity:output_type -> activity.ActivityResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_activity_proto_init() }
func file_api_proto_activity_proto_init() {
	if File_api_proto_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_activity_proto_rawDesc), len(file_api_proto_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_activity_proto_goTypes,
		DependencyIndexes: file_api_proto_activity_proto_depIdxs,
		MessageInfos:      file_api_proto_activity_proto_msgTypes,
	}.Build()
	File_api_proto_activity_proto = out.File
	file_api_proto_activity_proto_goTypes = nil
	file_api_proto_activity_proto_depIdxs = nil
}
